# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: testsrv.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtestsrv.proto\x12\ntest.repro\"\"\n\x0bTestRequest\x12\x13\n\x0btest_string\x18\x01 \x01(\t\"\'\n\x0cTestResponse\x12\x17\n\x0fresponse_string\x18\x01 \x01(\t2F\n\x07TestSrv\x12;\n\x04Test\x12\x17.test.repro.TestRequest\x1a\x18.test.repro.TestResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'testsrv_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TESTREQUEST']._serialized_start=29
  _globals['_TESTREQUEST']._serialized_end=63
  _globals['_TESTRESPONSE']._serialized_start=65
  _globals['_TESTRESPONSE']._serialized_end=104
  _globals['_TESTSRV']._serialized_start=106
  _globals['_TESTSRV']._serialized_end=176
# @@protoc_insertion_point(module_scope)
